# Generated by Django 4.1.3 on 2022-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=30)),
                ('product_id', models.TextField()),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.CharField(max_length=20)),
            ],
        ),
    ]
