# Generated by Django 4.1.3 on 2022-11-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_basketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='count',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
