# Generated by Django 4.1.3 on 2022-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('user_phone', models.CharField(max_length=15)),
                ('payment', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=250)),
                ('products', models.TextField()),
                ('products_price', models.CharField(max_length=200)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, choices=[('Y', 'Yangi'), ('M', 'Moderatsiya'), ('T', 'Tasdiqlangan'), ('B', 'Bekor qilingan')], default='Y', max_length=1)),
                ('telegram_id', models.CharField(max_length=15)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
