# Generated by Django 4.1.3 on 2022-12-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='adress',
            new_name='address',
        ),
    ]
